/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author 1GDAW04
 */
public class vMainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form vMainAdmin
     */
    public vMainAdmin() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelPerfiles = new javax.swing.JPanel();
        bAnadirUsuario = new org.edisoncor.gui.button.ButtonTask();
        bEliminarUsuario = new org.edisoncor.gui.button.ButtonTask();
        bEditarUsuario = new org.edisoncor.gui.button.ButtonTask();
        bVerListaUsuarios = new org.edisoncor.gui.button.ButtonTask();
        panelEscuderia = new javax.swing.JPanel();
        tabEscuderia = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelGestionEquipos = new javax.swing.JPanel();
        bAnadirEquipo = new org.edisoncor.gui.button.ButtonTask();
        bEliminarEquipo = new org.edisoncor.gui.button.ButtonTask();
        bEditarEquipo = new org.edisoncor.gui.button.ButtonTask();
        bVerDatosEquipo = new org.edisoncor.gui.button.ButtonTask();
        bMostrarTrabajadores = new org.edisoncor.gui.button.ButtonTask();
        panelGestionJugadores = new javax.swing.JPanel();
        bAnadirJugador = new org.edisoncor.gui.button.ButtonTask();
        bEliminarJugador = new org.edisoncor.gui.button.ButtonTask();
        bEditarJugador = new org.edisoncor.gui.button.ButtonTask();
        bVerJugador = new org.edisoncor.gui.button.ButtonTask();
        panelGestionJefes = new javax.swing.JPanel();
        bAnadirJefe = new org.edisoncor.gui.button.ButtonTask();
        bEliminarJefe = new org.edisoncor.gui.button.ButtonTask();
        bEditarJefe = new org.edisoncor.gui.button.ButtonTask();
        bVerJefes = new org.edisoncor.gui.button.ButtonTask();
        panelTorneos = new javax.swing.JPanel();
        bIniciarTorneo = new org.edisoncor.gui.button.ButtonTask();
        bEliminarTorneo = new org.edisoncor.gui.button.ButtonTask();
        bAdministrarTorneo = new org.edisoncor.gui.button.ButtonTask();
        bVerTorneos = new org.edisoncor.gui.button.ButtonTask();
        panelGeneral = new javax.swing.JPanel();
        bImprimirJornadas = new org.edisoncor.gui.button.ButtonAction();
        bImprimirClasificacion = new org.edisoncor.gui.button.ButtonAction();
        bInsertarResultados = new org.edisoncor.gui.button.ButtonAction();
        bJornadasRandom = new org.edisoncor.gui.button.ButtonAction();
        bTorneoRandom = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPerfiles.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50));

        bAnadirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoAñadir.png"))); // NOI18N
        bAnadirUsuario.setText("Añadir Usuario");
        bAnadirUsuario.setDescription(" ");
        bAnadirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnadirUsuarioActionPerformed(evt);
            }
        });
        panelPerfiles.add(bAnadirUsuario);

        bEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEliminar.png"))); // NOI18N
        bEliminarUsuario.setText("Eliminar Usuario");
        bEliminarUsuario.setDefaultCapable(false);
        bEliminarUsuario.setDescription(" ");
        bEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarUsuarioActionPerformed(evt);
            }
        });
        panelPerfiles.add(bEliminarUsuario);

        bEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEditar.png"))); // NOI18N
        bEditarUsuario.setText("Editar Usuario");
        bEditarUsuario.setDescription(" ");
        bEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarUsuarioActionPerformed(evt);
            }
        });
        panelPerfiles.add(bEditarUsuario);

        bVerListaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoBuscar.png"))); // NOI18N
        bVerListaUsuarios.setText("Ver Lista Usarios");
        bVerListaUsuarios.setDescription(" ");
        bVerListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerListaUsuariosActionPerformed(evt);
            }
        });
        panelPerfiles.add(bVerListaUsuarios);

        tabGeneral.addTab("          PERFILES          ", panelPerfiles);

        tabEscuderia.setBackground(new java.awt.Color(102, 153, 255));

        panelGestionEquipos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        bAnadirEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoAñadir.png"))); // NOI18N
        bAnadirEquipo.setText("Añadir Equipo");
        bAnadirEquipo.setDescription(" ");
        bAnadirEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnadirEquipoActionPerformed(evt);
            }
        });
        panelGestionEquipos.add(bAnadirEquipo);

        bEliminarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEliminar.png"))); // NOI18N
        bEliminarEquipo.setText("Eliminar Equipo");
        bEliminarEquipo.setAlignmentX(0.5F);
        bEliminarEquipo.setDefaultCapable(false);
        bEliminarEquipo.setDescription(" ");
        bEliminarEquipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bEliminarEquipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEliminarEquipo.setMargin(new java.awt.Insets(30, 50, 2, 14));
        bEliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarEquipoActionPerformed(evt);
            }
        });
        panelGestionEquipos.add(bEliminarEquipo);

        bEditarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEditar.png"))); // NOI18N
        bEditarEquipo.setText("Editar Equipo");
        bEditarEquipo.setDescription(" ");
        bEditarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarEquipoActionPerformed(evt);
            }
        });
        panelGestionEquipos.add(bEditarEquipo);

        bVerDatosEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoBuscar.png"))); // NOI18N
        bVerDatosEquipo.setText("Ver Datos Equipo");
        bVerDatosEquipo.setDescription(" ");
        bVerDatosEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerDatosEquipoActionPerformed(evt);
            }
        });
        panelGestionEquipos.add(bVerDatosEquipo);

        bMostrarTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEquipo.png"))); // NOI18N
        bMostrarTrabajadores.setText("Ver Trabajadores                    ");
        bMostrarTrabajadores.setDescription("Trabajadores de un equipo");
        bMostrarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarTrabajadoresActionPerformed(evt);
            }
        });
        panelGestionEquipos.add(bMostrarTrabajadores);

        tabEscuderia.addTab("Gestion Equipos                           ", panelGestionEquipos);

        panelGestionJugadores.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        bAnadirJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoAñadir.png"))); // NOI18N
        bAnadirJugador.setText("Añadir Jugador");
        bAnadirJugador.setDescription(" ");
        bAnadirJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnadirJugadorActionPerformed(evt);
            }
        });
        panelGestionJugadores.add(bAnadirJugador);

        bEliminarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEliminar.png"))); // NOI18N
        bEliminarJugador.setText("Eliminar Jugador");
        bEliminarJugador.setDefaultCapable(false);
        bEliminarJugador.setDescription(" ");
        bEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarJugadorActionPerformed(evt);
            }
        });
        panelGestionJugadores.add(bEliminarJugador);

        bEditarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEditar.png"))); // NOI18N
        bEditarJugador.setText("Editar Jugador");
        bEditarJugador.setDescription(" ");
        bEditarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarJugadorActionPerformed(evt);
            }
        });
        panelGestionJugadores.add(bEditarJugador);

        bVerJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoBuscar.png"))); // NOI18N
        bVerJugador.setText("Ver Jugador");
        bVerJugador.setDescription(" ");
        bVerJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerJugadorActionPerformed(evt);
            }
        });
        panelGestionJugadores.add(bVerJugador);

        tabEscuderia.addTab("     Gestion Jugadores     ", panelGestionJugadores);

        panelGestionJefes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        bAnadirJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoAñadir.png"))); // NOI18N
        bAnadirJefe.setText("Añadir Jefe");
        bAnadirJefe.setDescription(" ");
        bAnadirJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnadirJefeActionPerformed(evt);
            }
        });
        panelGestionJefes.add(bAnadirJefe);

        bEliminarJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEliminar.png"))); // NOI18N
        bEliminarJefe.setText("Eliminar Jefe");
        bEliminarJefe.setDefaultCapable(false);
        bEliminarJefe.setDescription(" ");
        bEliminarJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarJefeActionPerformed(evt);
            }
        });
        panelGestionJefes.add(bEliminarJefe);

        bEditarJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEditar.png"))); // NOI18N
        bEditarJefe.setText("Editar Jefe");
        bEditarJefe.setDescription(" ");
        bEditarJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarJefeActionPerformed(evt);
            }
        });
        panelGestionJefes.add(bEditarJefe);

        bVerJefes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoBuscar.png"))); // NOI18N
        bVerJefes.setText("Ver Jefes");
        bVerJefes.setDescription(" ");
        bVerJefes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerJefesActionPerformed(evt);
            }
        });
        panelGestionJefes.add(bVerJefes);

        tabEscuderia.addTab("Gestion Jefes                   ", panelGestionJefes);

        javax.swing.GroupLayout panelEscuderiaLayout = new javax.swing.GroupLayout(panelEscuderia);
        panelEscuderia.setLayout(panelEscuderiaLayout);
        panelEscuderiaLayout.setHorizontalGroup(
            panelEscuderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabEscuderia, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE)
        );
        panelEscuderiaLayout.setVerticalGroup(
            panelEscuderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscuderiaLayout.createSequentialGroup()
                .addComponent(tabEscuderia, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabGeneral.addTab("          ESCUDERIA             ", panelEscuderia);

        panelTorneos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        bIniciarTorneo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoInicio.png"))); // NOI18N
        bIniciarTorneo.setText("Iniciar Torneo");
        bIniciarTorneo.setDescription(" ");
        panelTorneos.add(bIniciarTorneo);

        bEliminarTorneo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEliminar.png"))); // NOI18N
        bEliminarTorneo.setText("Eliminar Torneo");
        bEliminarTorneo.setDefaultCapable(false);
        bEliminarTorneo.setDescription(" ");
        bEliminarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarTorneoActionPerformed(evt);
            }
        });
        panelTorneos.add(bEliminarTorneo);

        bAdministrarTorneo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoEditar.png"))); // NOI18N
        bAdministrarTorneo.setText("Administrar Torneo");
        bAdministrarTorneo.setDescription(" ");
        bAdministrarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdministrarTorneoActionPerformed(evt);
            }
        });
        panelTorneos.add(bAdministrarTorneo);

        bVerTorneos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Imagenes/iconoBuscar.png"))); // NOI18N
        bVerTorneos.setText("Ver Torneos");
        bVerTorneos.setDescription(" ");
        bVerTorneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerTorneosActionPerformed(evt);
            }
        });
        panelTorneos.add(bVerTorneos);

        tabGeneral.addTab("          TORNEOS          ", panelTorneos);

        panelGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones Generales", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 14))); // NOI18N
        panelGeneral.setForeground(new java.awt.Color(0, 0, 51));
        panelGeneral.setLayout(new java.awt.GridLayout(3, 2, 40, 50));

        bImprimirJornadas.setText("IMPRIMIR TODAS LAS JORNADAS");
        panelGeneral.add(bImprimirJornadas);

        bImprimirClasificacion.setText("IMPRIMIR CLASIFICACION GENERAL");
        panelGeneral.add(bImprimirClasificacion);

        bInsertarResultados.setText("INSERTAR RESULTADOS JORNADA");
        panelGeneral.add(bInsertarResultados);

        bJornadasRandom.setText("JORNADAS RANDOM");
        panelGeneral.add(bJornadasRandom);

        bTorneoRandom.setText("FINALIZAR TORNEO RANDOM");
        panelGeneral.add(bTorneoRandom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMostrarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMostrarTrabajadoresActionPerformed

    private void bEditarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarEquipoActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Selleciona equipo a modificar", "Equipo: ", "modequipo");
    }//GEN-LAST:event_bEditarEquipoActionPerformed

    private void bAnadirJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnadirJefeActionPerformed
        torneoes.TorneoES.abrirVentanaCrearJefe();
    }//GEN-LAST:event_bAnadirJefeActionPerformed

    private void bEditarJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarJefeActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Selecciona jefe a modificar", "Jefe", "modjefe");
    }//GEN-LAST:event_bEditarJefeActionPerformed

    private void bEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarUsuarioActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Selleccione perfil a editar", "Perfil:", "modperfil");
    }//GEN-LAST:event_bEditarUsuarioActionPerformed

    private void bEliminarJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarJefeActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Seleccione jefe a eliminar", "Jefe:", "borrarjefe");
    }//GEN-LAST:event_bEliminarJefeActionPerformed

    private void bVerJefesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerJefesActionPerformed
        torneoes.TorneoES.abrirVentanaAllJefe();
    }//GEN-LAST:event_bVerJefesActionPerformed

    private void bVerTorneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerTorneosActionPerformed
        torneoes.TorneoES.abrirVentanaAllTorneo();
    }//GEN-LAST:event_bVerTorneosActionPerformed

    private void bAdministrarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdministrarTorneoActionPerformed
        torneoes.TorneoES.abrirVentanaModTorneo();
    }//GEN-LAST:event_bAdministrarTorneoActionPerformed

    private void bEliminarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarTorneoActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Seleccione torneo a eliminar", "Torneo:", "borrartorneo");
    }//GEN-LAST:event_bEliminarTorneoActionPerformed

    private void bAnadirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnadirUsuarioActionPerformed
        torneoes.TorneoES.abrirVCrearPerfil();
    }//GEN-LAST:event_bAnadirUsuarioActionPerformed

    private void bEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarUsuarioActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Sellecione usuario a eliminar", "Usuario:", "borrarperfil");
    }//GEN-LAST:event_bEliminarUsuarioActionPerformed

    private void bVerListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerListaUsuariosActionPerformed
        try {
            torneoes.TorneoES.abrirVAllPerfil();
        } catch (Exception ex) {
            Logger.getLogger(vMainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bVerListaUsuariosActionPerformed

    private void bAnadirEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnadirEquipoActionPerformed
        torneoes.TorneoES.abrirVCrearEquipo();
    }//GEN-LAST:event_bAnadirEquipoActionPerformed

    private void bEliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarEquipoActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Selecciona equipo a eliminar", "Equipo: ", "borrarequipo");
    }//GEN-LAST:event_bEliminarEquipoActionPerformed

    private void bVerDatosEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerDatosEquipoActionPerformed
        try {
            torneoes.TorneoES.abrirVAllEquipo();
        } catch (Exception ex) {
            Logger.getLogger(vMainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bVerDatosEquipoActionPerformed

    private void bAnadirJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnadirJugadorActionPerformed
        try {
            torneoes.TorneoES.abrirVCrearJugador();
        } catch (Exception ex) {
            Logger.getLogger(vMainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bAnadirJugadorActionPerformed

    private void bEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarJugadorActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Seleccione jugador a eliminar", "Jugador: ", "borrarjugador");
    }//GEN-LAST:event_bEliminarJugadorActionPerformed

    private void bEditarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarJugadorActionPerformed
        torneoes.TorneoES.abrirVentanaSeleccion("Seleccione jugador a modificar", "Jugador: ", "modjugador");
    }//GEN-LAST:event_bEditarJugadorActionPerformed

    private void bVerJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerJugadorActionPerformed
        try {
            torneoes.TorneoES.abrirVCrearJugador();
        } catch (Exception ex) {
            Logger.getLogger(vMainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bVerJugadorActionPerformed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask bAdministrarTorneo;
    private org.edisoncor.gui.button.ButtonTask bAnadirEquipo;
    private org.edisoncor.gui.button.ButtonTask bAnadirJefe;
    private org.edisoncor.gui.button.ButtonTask bAnadirJugador;
    private org.edisoncor.gui.button.ButtonTask bAnadirUsuario;
    private org.edisoncor.gui.button.ButtonTask bEditarEquipo;
    private org.edisoncor.gui.button.ButtonTask bEditarJefe;
    private org.edisoncor.gui.button.ButtonTask bEditarJugador;
    private org.edisoncor.gui.button.ButtonTask bEditarUsuario;
    private org.edisoncor.gui.button.ButtonTask bEliminarEquipo;
    private org.edisoncor.gui.button.ButtonTask bEliminarJefe;
    private org.edisoncor.gui.button.ButtonTask bEliminarJugador;
    private org.edisoncor.gui.button.ButtonTask bEliminarTorneo;
    private org.edisoncor.gui.button.ButtonTask bEliminarUsuario;
    private org.edisoncor.gui.button.ButtonAction bImprimirClasificacion;
    private org.edisoncor.gui.button.ButtonAction bImprimirJornadas;
    private org.edisoncor.gui.button.ButtonTask bIniciarTorneo;
    private org.edisoncor.gui.button.ButtonAction bInsertarResultados;
    private org.edisoncor.gui.button.ButtonAction bJornadasRandom;
    private org.edisoncor.gui.button.ButtonTask bMostrarTrabajadores;
    private org.edisoncor.gui.button.ButtonAction bTorneoRandom;
    private org.edisoncor.gui.button.ButtonTask bVerDatosEquipo;
    private org.edisoncor.gui.button.ButtonTask bVerJefes;
    private org.edisoncor.gui.button.ButtonTask bVerJugador;
    private org.edisoncor.gui.button.ButtonTask bVerListaUsuarios;
    private org.edisoncor.gui.button.ButtonTask bVerTorneos;
    private javax.swing.JPanel panelEscuderia;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelGestionEquipos;
    private javax.swing.JPanel panelGestionJefes;
    private javax.swing.JPanel panelGestionJugadores;
    private javax.swing.JPanel panelPerfiles;
    private javax.swing.JPanel panelTorneos;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabEscuderia;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabGeneral;
    // End of variables declaration//GEN-END:variables
}
