/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import UML.Equipo;
import UML.Perfil;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 1gdaw06
 */
public class vSelector extends javax.swing.JDialog {

    String ventana;
    String tipoSeleccion;
    
    public vSelector(java.awt.Frame parent, boolean modal, String titulo, String tipoSeleccion, String ventana) {
        super(parent, modal);
        this.ventana = ventana;
        this.tipoSeleccion = tipoSeleccion;
        try {
            initComponents();
            personalizarVentana(titulo, tipoSeleccion);
            torneoes.TorneoES.llenarComboBoxJefes(cbSeleccion);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ha ocurido un error inesperado: " + ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        lTitulo = new org.edisoncor.gui.label.LabelRect();
        cbSeleccion = new org.edisoncor.gui.comboBox.ComboBoxRect();
        lSelector = new javax.swing.JLabel();
        bAceptar = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 153, 0));

        lTitulo.setBackground(new java.awt.Color(255, 153, 0));
        lTitulo.setText("Formulario nuevo jefe");
        lTitulo.setColorDeBorde(new java.awt.Color(255, 153, 51));

        lSelector.setText("LabelManipulable");

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lSelector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSelector))
                .addGap(31, 31, 31)
                .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            String seleccionado = String.valueOf(cbSeleccion.getSelectedItem());
            int id = Integer.parseInt(seleccionado.substring(0, seleccionado.indexOf(":")));
            switch(ventana){
                case "modjefe":
                    torneoes.TorneoES.abrirVentanaModJefe(id);
                    break;
                case "borrarjefe":
                    BD.tablaJefes.eliminarJefe(id);
                    JOptionPane.showMessageDialog(null, "Se ha borrado el jefe seleccionado");
                    break;
                case "modequipo":
                    Equipo equipoActual = torneoes.TorneoES.obtenerEquipo(String.valueOf(id));
                    torneoes.TorneoES.abrirVModEquipo(equipoActual);
                    break;
                case "borrarequipo":
                    BD.tablaEquipos.eliminarEquipo(String.valueOf(id));
                    JOptionPane.showMessageDialog(null, "Se ha borrado el equipo seleccionado");
                case "modperfil":
                    Perfil perfilActual = torneoes.TorneoES.obtenerPerfil(String.valueOf(id));
                    torneoes.TorneoES.abrirVModPerfil(perfilActual);
                    break;
                case "borrarperfil":
                    BD.tablaPerfiles.eliminarPerfil(String.valueOf(id));
                    JOptionPane.showMessageDialog(null, "Se ha borrado el perfil seleccionado");
                    break;
                
                    
            }
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_bAceptarActionPerformed

    
    
    public void personalizarVentana(String titulo, String label){
        lTitulo.setText(titulo);
        lSelector.setText(label);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction bAceptar;
    private org.edisoncor.gui.comboBox.ComboBoxRect cbSeleccion;
    private javax.swing.JLabel lSelector;
    private org.edisoncor.gui.label.LabelRect lTitulo;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
