CREATE OR REPLACE PACKAGE VARIABLES_TABLA_MUTANTES IS
IDEQUIPO NUMBER;
END;

CREATE OR REPLACE TRIGGER MAX_JUGADORES_FILA 
BEFORE UPDATE OF IDEQUIPO OR INSERT ON JUGADORES 
FOR EACH ROW
DECLARE
V_MENSAJE VARCHAR2(1000);
BEGIN
    VARIABLES_TABLA_MUTANTES.IDEQUIPO := :NEW.IDEQUIPO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001,'No se ha encontrado juggadores con ese equipo');
    WHEN OTHERS THEN 
        V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
        SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;



CREATE OR REPLACE TRIGGER MAX_JUGADORES_SENTENCIA 
AFTER UPDATE OF IDEQUIPO OR INSERT ON JUGADORES 
DECLARE
N_JUGADORES NUMBER;
MAXIMO_NUMERO_JUGADORES EXCEPTION;
V_MENSAJE VARCHAR2(1000);
BEGIN
    SELECT COUNT(*) INTO N_JUGADORES FROM JUGADORES
    WHERE IDEQUIPO=VARIABLES_TABLA_MUTANTES.IDEQUIPO;
    IF N_JUGADORES=6 OR N_JUGADORES>6 THEN
        V_MENSAJE:='El equipo ya tiene el maximo numero de jugadores permitidos';
        RAISE MAXIMO_NUMERO_JUGADORES;
    END IF;
EXCEPTION
    WHEN MAXIMO_NUMERO_JUGADORES THEN
        RAISE_APPLICATION_ERROR(-20001, V_MENSAJE);
    WHEN OTHERS THEN 
        V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
        SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;



