CREATE OR REPLACE PACKAGE PKG_FUNCIONES IS
    FUNCTION COMPROBAR_MIN_JUGADORES
    RETURN BOOLEAN;
    PROCEDURE EMPLE_EQUIPO(V_IDEQUIPO IN EQUIPOS.IDEQUIPO%TYPE,
                                        CEMPLES OUT SYS_REFCURSOR);
    PROCEDURE TOP_3_EQUIPOS (
                C OUT SYS_REFCURSOR);
END;
/
CREATE OR REPLACE PACKAGE BODY PKG_FUNCIONES IS

FUNCTION COMPROBAR_MIN_JUGADORES
    RETURN BOOLEAN
    IS
        CURSOR MICURSOR IS SELECT DISTINCT(IDEQUIPO) FROM EQUIPOS;
        IDE EQUIPOS.IDEQUIPO%TYPE;
        N_JUGADORES NUMBER;
        V_MENSAJE VARCHAR2(1000);
    BEGIN
        OPEN MICURSOR;
        FETCH MICURSOR INTO IDE;
        WHILE MICURSOR%FOUND LOOP
            SELECT COUNT(*) INTO N_JUGADORES FROM JUGADORES
            WHERE IDEQUIPO=IDE;
            IF N_JUGADORES < 2 THEN
                RETURN FALSE;
            END IF;
            FETCH MICURSOR INTO IDE;
        END LOOP;
        RETURN TRUE;
    EXCEPTION
        WHEN OTHERS THEN 
            V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
            SQLERRM;
            RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
    END COMPROBAR_MIN_JUGADORES;

PROCEDURE EMPLE_EQUIPO(V_IDEQUIPO IN EQUIPOS.IDEQUIPO%TYPE,
                                        CEMPLES OUT SYS_REFCURSOR)
    IS
        V_MENSAJE VARCHAR2(1000);
        
    BEGIN
       
        OPEN CEMPLES FOR
            SELECT P.IDPERSONA, P.DNI, P.NOMBRE, P.APELLIDO, P.FECHA_NACIMIENTO, 
            P.SUELDO, P.TELEFONO, P.FECHA_CONTRATO, P.NACIONALIDAD
            FROM PERSONAS P
            WHERE P.IDPERSONA IN (SELECT IDJEFE
                                FROM EQUIPOS E
                                WHERE E.IDEQUIPO = V_IDEQUIPO)
            OR P.IDPERSONA IN (SELECT IDPREPARADOR
                                FROM EQUIPOS E
                                WHERE E.IDEQUIPO = V_IDEQUIPO)
            OR P.IDPERSONA IN (SELECT IDENTRENADOR
                                FROM EQUIPOS E
                                WHERE E.IDEQUIPO = V_IDEQUIPO)
            OR P.IDPERSONA IN (SELECT IDPERSONA
                                FROM TRABAJADORES T
                                WHERE T.IDEQUIPO = V_IDEQUIPO);  
    EXCEPTION
        WHEN OTHERS THEN 
            V_MENSAJE := 'ERROR ORACLE : '|| TO_CHAR(SQLCODE) ||', '||SQLERRM;
            RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
    END EMPLE_EQUIPO;

PROCEDURE TOP_3_EQUIPOS (
C OUT SYS_REFCURSOR)
IS
    V_MENSAJE VARCHAR2(1000);
BEGIN 
    OPEN C FOR SELECT * FROM (SELECT IDEQUIPO, SUM(PUNTUACION) AS "PUNTUACION_TOTAL" FROM PARTIDOS_JUGADOS
            GROUP BY IDEQUIPO
            ORDER BY PUNTUACION_TOTAL DESC)
            WHERE ROWNUM < 4;
EXCEPTION
    WHEN OTHERS THEN 
        V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
        SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;
END;