CREATE OR REPLACE TRIGGER REQUISITOS_TORNEO
BEFORE UPDATE OF ESTADO ON TORNEOS
DECLARE
MIN_JUGADORES_OK BOOLEAN;
N_EQUIPOS NUMBER;
MIN_2_JUGADORES EXCEPTION;
NUM_EQUIPOS_IMPAR EXCEPTION;
V_MENSAJE VARCHAR2(1000);
BEGIN
MIN_JUGADORES_OK:=COMPROBAR_MIN_JUGADORES();
IF MIN_JUGADORES_OK THEN
    SELECT COUNT(*) INTO N_EQUIPOS FROM EQUIPOS;
    IF MOD(N_EQUIPOS, 2) != 0 THEN
        RAISE NUM_EQUIPOS_IMPAR;
    END IF;
    RAISE MIN_2_JUGADORES;
END IF;
EXCEPTION
    WHEN NUM_EQUIPOS_IMPAR THEN
        V_MENSAJE:= 'Debe haber un numero par de equipos para iniciar torneo';
        RAISE_APPLICATION_ERROR(-20003, V_MENSAJE);
    WHEN MIN_2_JUGADORES THEN
        V_MENSAJE:= 'Debe haber un minimo de 2 jugadores para iniciar torneo';
        RAISE_APPLICATION_ERROR(-20004, V_MENSAJE);
    WHEN OTHERS THEN 
        V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
        SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;
    