DROP TRIGGER CALENDARIO_CERRADO_JUGADORES;
DROP TRIGGER CALENDARIO_CERRADO_EQUIPOS;

CREATE OR REPLACE TRIGGER CALENDARIO_CERRADO_EQUIPOS
BEFORE UPDATE OR INSERT OR DELETE
ON EQUIPOS
DECLARE 
ESTADO_TORNEO VARCHAR2(30);
BEGIN
    SELECT UPPER(ESTADO) INTO ESTADO_TORNEO
    FROM TORNEOS;
    IF ESTADO_TORNEO IN UPPER('CERRADO')
        THEN RAISE_APPLICATION_ERROR(-20100, 'EL TORNEO ESTA CERRADO');
    END IF;
END;

CREATE OR REPLACE TRIGGER CALENDARIO_CERRADO_JUGADORES
BEFORE UPDATE OR INSERT OR DELETE
ON JUGADORES
DECLARE 
ESTADO_TORNEO VARCHAR2(30);
BEGIN
    SELECT UPPER(ESTADO) INTO ESTADO_TORNEO
    FROM TORNEOS;
    IF ESTADO_TORNEO IN UPPER('CERRADO')
        THEN RAISE_APPLICATION_ERROR(-20100, 'EL TORNEO ESTA CERRADO');
    END IF; 
END;