DROP TRIGGER SUELDO_ANUAL;

CREATE OR REPLACE TRIGGER SUELDO_ANUAL
BEFORE INSERT OR UPDATE
ON JUGADORES 
FOR EACH ROW
DECLARE 
SUMASALARIO NUMBER;
SALARIO_EXCESIVO EXCEPTION;
V_MENSAJE VARCHAR2(500);
BEGIN
    SELECT SUM(P.SUELDO)*12 INTO SUMASALARIO
    FROM PERSONAS P, JUGADORES J 
    WHERE P.IDPERSONA = J.IDPERSONA
    GROUP BY J.IDEQUIPO;
    IF SUMASALARIO > 200000
        THEN V_MENSAJE := 'EL SALARIO EXCEDE EL LIMITE ANUAL PERMITIDO';
        RAISE SALARIO_EXCESIVO;
    END IF;
EXCEPTION
WHEN SALARIO_EXCESIVO THEN
        RAISE_APPLICATION_ERROR(-20001, V_MENSAJE);
WHEN OTHERS THEN 
        V_MENSAJE := 'ERROR ORACLE : '|| TO_CHAR(SQLCODE) ||', '||SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;