
CREATE OR REPLACE TRIGGER SALARIO_MIN_FILA
BEFORE INSERT OR UPDATE OF SUELDO ON PERSONAS
FOR EACH ROW
DECLARE
V_MENSAJE VARCHAR2(1000);
BEGIN
    VARIABLES_TABLA_MUTANTES.SUELDO_PERSONA := :NEW.SUELDO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001,'No se ha encontrado juggadores con ese equipo');
    WHEN OTHERS THEN 
        V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
        SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;
/

CREATE OR REPLACE TRIGGER SALARIO_MIN_SENTENCIA 
AFTER UPDATE OF SUELDO OR INSERT ON PERSONAS 
DECLARE
SUELDO_MIN_ERROR EXCEPTION;
V_MENSAJE VARCHAR2(1000);
BEGIN
    IF VARIABLES_TABLA_MUTANTES.SUELDO_PERSONA < VARIABLES_GLOBALES.SUELDO_MINIMO_INTER THEN
        RAISE SUELDO_MIN_ERROR;
    END IF;
EXCEPTION
    WHEN SUELDO_MIN_ERROR THEN
        V_MENSAJE:='El salario introducido esta por debajo del minimo permitido';
        RAISE_APPLICATION_ERROR(-20001, V_MENSAJE);
    WHEN OTHERS THEN 
        V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
        SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;