DROP TRIGGER CALENDARIO_CERRADO_JUGADORES;
DROP TRIGGER CALENDARIO_CERRADO_EQUIPOS;

CREATE OR REPLACE TRIGGER CALENDARIO_CERRADO_EQUIPOS
BEFORE UPDATE OR INSERT OR DELETE
ON EQUIPOS
DECLARE 
N_TORNEOS_CERRADOS VARCHAR2(30);
TORNEO_CERRADO EXCEPTION;
V_MENSAJE VARCHAR2(1000);
BEGIN
    SELECT COUNT(*) INTO N_TORNEOS_CERRADOS
    FROM TORNEOS WHERE ESTADO='CERRADO';
    IF N_TORNEOS_CERRADOS > 0 THEN
        RAISE TORNEO_CERRADO;
    END IF;
EXCEPTION
    WHEN TORNEO_CERRADO THEN
        V_MENSAJE:= 'HAY UN TORNEO CERRADO';
        RAISE_APPLICATION_ERROR(-20100, V_MENSAJE);
    WHEN OTHERS THEN 
        V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
        SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;

CREATE OR REPLACE TRIGGER CALENDARIO_CERRADO_JUGADORES
BEFORE UPDATE OR INSERT OR DELETE
ON JUGADORES
DECLARE
N_TORNEOS_CERRADOS VARCHAR2(30);
TORNEO_CERRADO EXCEPTION;
V_MENSAJE VARCHAR2(1000);
BEGIN
    SELECT COUNT(*) INTO N_TORNEOS_CERRADOS
    FROM TORNEOS WHERE ESTADO='CERRADO';
    IF N_TORNEOS_CERRADOS > 0 THEN
        RAISE TORNEO_CERRADO;
    END IF;
EXCEPTION
    WHEN TORNEO_CERRADO THEN
        V_MENSAJE:= 'HAY UN TORNEO CERRADO';
        RAISE_APPLICATION_ERROR(-20100, V_MENSAJE);
    WHEN OTHERS THEN 
        V_MENSAJE:= 'Se ha detectado el error ' || sqlcode || ': ' ||
        SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, V_MENSAJE);
END;