/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Jefe;

import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 1GDAW04
 */
public class vCrearJefe extends javax.swing.JFrame {

   
    String dni;
    String nombre;
    String apellido;
    LocalDate fechaNacimiento;
    String sueldo;
    String telefono;
    LocalDate fechaContrato;
    LocalDate fechaFinContrato;
    String nacionalidad;
    
    public vCrearJefe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldRectImage1 = new org.edisoncor.gui.textField.TextFieldRectImage();
        textFieldRectImage2 = new org.edisoncor.gui.textField.TextFieldRectImage();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDni = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel3 = new javax.swing.JLabel();
        tfApellido = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel4 = new javax.swing.JLabel();
        dpFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        jLabel5 = new javax.swing.JLabel();
        tfSueldo = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel6 = new javax.swing.JLabel();
        tfTelefono = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        dpFechaContrato = new com.github.lgooddatepicker.components.DatePicker();
        jLabel8 = new javax.swing.JLabel();
        dpFechaFinContrato = new com.github.lgooddatepicker.components.DatePicker();
        jLabel9 = new javax.swing.JLabel();
        tfNacionalidad = new org.edisoncor.gui.textField.TextFieldRound();
        labelRect2 = new org.edisoncor.gui.label.LabelRect();
        bGuardar = new org.edisoncor.gui.button.ButtonAction();
        panel1 = new org.edisoncor.gui.panel.Panel();

        textFieldRectImage1.setText("textFieldRectImage1");

        textFieldRectImage2.setText("textFieldRectImage2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 4, 5, 25));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("DNI:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);

        tfDni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfDni.setCaretColor(new java.awt.Color(255, 204, 102));
        tfDni.setDisabledTextColor(new java.awt.Color(255, 204, 153));
        tfDni.setSelectionColor(new java.awt.Color(255, 153, 102));
        jPanel1.add(tfDni);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);

        tfNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfNombre.setCaretColor(new java.awt.Color(255, 204, 102));
        tfNombre.setDisabledTextColor(new java.awt.Color(255, 204, 153));
        tfNombre.setSelectionColor(new java.awt.Color(255, 153, 102));
        jPanel1.add(tfNombre);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3);

        tfApellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfApellido.setCaretColor(new java.awt.Color(255, 204, 102));
        tfApellido.setDisabledTextColor(new java.awt.Color(255, 204, 153));
        tfApellido.setSelectionColor(new java.awt.Color(255, 153, 102));
        jPanel1.add(tfApellido);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha Nacimiento:");
        jPanel1.add(jLabel4);
        jPanel1.add(dpFechaNacimiento);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sueldo:");
        jPanel1.add(jLabel5);

        tfSueldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfSueldo.setCaretColor(new java.awt.Color(255, 204, 102));
        tfSueldo.setDisabledTextColor(new java.awt.Color(255, 204, 153));
        tfSueldo.setSelectionColor(new java.awt.Color(255, 153, 102));
        jPanel1.add(tfSueldo);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6);

        tfTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfTelefono.setCaretColor(new java.awt.Color(255, 204, 102));
        tfTelefono.setDisabledTextColor(new java.awt.Color(255, 204, 153));
        tfTelefono.setSelectionColor(new java.awt.Color(255, 153, 102));
        jPanel1.add(tfTelefono);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Fecha Contrato:");
        jPanel1.add(jLabel7);
        jPanel1.add(dpFechaContrato);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Fecha Fin Contrato:");
        jPanel1.add(jLabel8);
        jPanel1.add(dpFechaFinContrato);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nacionalidad:");
        jPanel1.add(jLabel9);

        tfNacionalidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfNacionalidad.setCaretColor(new java.awt.Color(255, 204, 102));
        tfNacionalidad.setDisabledTextColor(new java.awt.Color(255, 204, 153));
        tfNacionalidad.setSelectionColor(new java.awt.Color(255, 153, 102));
        jPanel1.add(tfNacionalidad);

        labelRect2.setText("Formulario nuevo jefe");
        labelRect2.setBackground(new java.awt.Color(255, 153, 0));
        labelRect2.setColorDeBorde(new java.awt.Color(255, 153, 51));

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        panel1.setLayout(new java.awt.GridLayout(5, 4, 5, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addContainerGap(425, Short.MAX_VALUE))
            .addComponent(labelRect2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(340, 340, 340)
                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        dni = tfDni.getText();
        nombre = tfNombre.getText();
        apellido = tfApellido.getText();
        fechaNacimiento = dpFechaNacimiento.getDate();
        sueldo = tfSueldo.getText();
        telefono = tfTelefono.getText();
        fechaContrato = dpFechaContrato.getDate();
        fechaFinContrato = dpFechaFinContrato.getDate();
        nacionalidad = tfNacionalidad.getText();
        if(validarDatos()){
            try {
                torneoes.TorneoES.insertarJefe(dni, nombre, apellido, fechaNacimiento, Double.parseDouble(sueldo), telefono, fechaContrato, fechaFinContrato, nacionalidad);
                System.out.println("Se ha insertado el jefe en la BD.");
            } catch (Exception ex) {
                System.out.println("Ha habido un problema al insertar el jefe en la BD.");
                System.out.println(ex.getMessage() +ex.getClass());
            }
        }
    }//GEN-LAST:event_bGuardarActionPerformed


    public boolean validarDatos(){        
        try{
            if(dni.matches("[0-9]{8}[a-z A-Z]{1}")){
                if(nombre.matches("[a-zA-Z]{3,}")){
                    if(apellido.matches("[a-zA-Z]{3,}")){
                        if(sueldo.matches("\\d{3,6}")){
                            if(telefono.matches("\\d{9}")){
                                if(fechaFinContrato.isAfter(fechaContrato)){
                                    if(!nacionalidad.isEmpty()){
                                        return true;
                                    }else{
                                        throw new Excepciones.Java.campoVacio("El campo nacionalidad no puede estar vacio");
                                    }
                                }else{
                                throw new Exception("La fecha fin contrato no puede ser anterior a la fecha de inicio del contrato");
                            }
                            }else{
                                throw new Excepciones.Java.formatoNoValido("El campo telefono no tiene el formato correcto");
                            }
                        }else{
                            throw new Excepciones.Java.formatoNoValido("El campo sueldo solo admite digitos con un minimo de 3 y maximo de 6 digitos");
                        }
                    }else{
                        throw new Excepciones.Java.formatoNoValido("El campo apellido ha de tener mas de 3 caracteres");
                    }
                }else{
                    throw new Excepciones.Java.formatoNoValido("El campo nombre ha de tener mas de 3 caracteres");
                }
            }else{
                throw new Excepciones.Java.formatoNoValido("El campo DNI no tiene el formato correcto");
            }
        }
        catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
                return false;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction bGuardar;
    private com.github.lgooddatepicker.components.DatePicker dpFechaContrato;
    private com.github.lgooddatepicker.components.DatePicker dpFechaFinContrato;
    private com.github.lgooddatepicker.components.DatePicker dpFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.label.LabelRect labelRect2;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.textField.TextFieldRectImage textFieldRectImage1;
    private org.edisoncor.gui.textField.TextFieldRectImage textFieldRectImage2;
    private org.edisoncor.gui.textField.TextFieldRound tfApellido;
    private org.edisoncor.gui.textField.TextFieldRound tfDni;
    private org.edisoncor.gui.textField.TextFieldRound tfNacionalidad;
    private org.edisoncor.gui.textField.TextFieldRound tfNombre;
    private org.edisoncor.gui.textField.TextFieldRound tfSueldo;
    private org.edisoncor.gui.textField.TextFieldRound tfTelefono;
    // End of variables declaration//GEN-END:variables
}
